### PR TITLE
JAI HIND

### PR DESCRIPTION
**Pull request by Akash2Sharma**
HINDUSTAN ZINDABAD

### CODE REVIEW

**Comment by v27u27** [comment]
please be professional, and make some pro pull requests, not just ant shunt... ok? you got that?

**Comment by Akash2Sharma** [comment]
Sir I am trying to learn  the techniques ,the process of working  and contributing to open source projects

**Comment by v27u27** [comment]
don't try to be over smart, bc hawabaazi karenge github pe...

**Comment by Akash2Sharma** [comment]
Only BINAYAK do dikhava +havabazi to impress everyone

**Comment by v27u27** [comment]
get the fuck out of here

**Pull request closed without merging**
